version: '3'
services:
  # app:
  #   container_name: api_nestjs
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   command: yarn start:dev
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db

  db:
    container_name: db-kuasar
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./docker/volumes/:/var/lib/postgresql/data

volumes:
  mysqldata: # driver: local
